baseURL = 'http://example.org/'
languageCode = 'ru-ru'
title = 'Rusanto (NovoRosiana) - Русский эсперантоид и ответ "Basic English". Имеет очень простую грамматику и легк для изучения'
theme = "archie"



[params]
	mode="auto"
	useCDN=false

[menu]
  [[menu.main]]
    name = "Translitor"
    url = "/merkato"
    weight = 1
    
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

