baseURL = 'http://example.org/'
languageCode = 'ru-ru'
defaultContentLanguage = 'en'
title = 'Rusanto (NovoRosiana) - Simplified Russian as "Basic English". Has very simple grammar and is easy to learn'
theme = "hugo-flex"


[params]
	mode="auto"
	useCDN=false
	width = '58rem'

[menu]
  [[menu.main]]
    name = "Translitor"
    url = "/merkato"
    weight = 1
    
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About (English)"
    url = "/about_en"
    weight = 2

  [[menu.main]]
    name = "Learn"
    url = "/learn"
    weight = 2
